### PR TITLE
Fixed Error When No Gift Sku Given

### PR DESCRIPTION
**Pull request by sprankhub**
There is an error when the user does not enter a gift SKU in the backend. This PR solves this issue.

I also thought about making the gift SKU field required. But since it is always shown, this is not possible.

### CODE REVIEW

**Comment by nkrambrock** [comment]
Thank you very much for the pull request. I fear I have to reject it: Once this is installed it is silently failing instead of an exception. This is no intention of me. Maybe a check in the backend would be useful - this is the moment where the user could do something with the info.

**Comment by sprankhub** [comment]
I have to insist on this issue. Currently, with an empty SKU, not only the functionality of the extension breaks, but the add to cart functionality does not work any more (at least with developer mode on - did not test without yet). Would it be possible and okay to check for an empty SKU when saving the rule and adding an error if the SKU is empty at this step?

**Comment by nkrambrock** [comment]
> Would it be possible and okay to check for an empty SKU when saving the rule and adding an error if the SKU is empty at this step?

Yes or course! I just want to avoid a silent fail in the frontend - a clear fail in the backend is a good idea. (It might also be an idea to check if the product exists - although this might change any time.) Do you want to file a new pull request?

**Comment by sprankhub** [comment]
Yeah, will do.

**Comment by sprankhub** [comment]
See #11.

**Pull request closed without merging**
